"""Public legal pages (privacy policy + terms of service).

These are unauthenticated on purpose: Meta requires a publicly reachable
privacy policy URL before an app can be published.
"""
from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

_PAGE_STYLE = """
body{font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
max-width:720px;margin:2.5rem auto;padding:0 1.25rem;line-height:1.65;color:#1f2937}
h1{font-size:1.6rem;margin-bottom:.25rem}h2{font-size:1.15rem;margin-top:1.75rem}
.updated{color:#6b7280;font-size:.9rem}li{margin:.35rem 0}
footer{margin-top:2.5rem;color:#6b7280;font-size:.85rem}
"""

PRIVACY_HTML = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy Policy &mdash; Multi-Tenant WhatsApp Agent</title>
<style>{_PAGE_STYLE}</style></head>
<body>
<h1>Privacy Policy</h1>
<p class="updated">Last updated: October 1, 2026</p>
<p><strong>Multi-Tenant WhatsApp Agent</strong> is a demo project that connects
an AI assistant to a WhatsApp business number so it can answer customer messages.
This policy explains what data the demo handles.</p>

<h2>Data we collect</h2>
<ul>
<li><strong>WhatsApp phone numbers</strong> of people who message a connected
business number.</li>
<li><strong>Message contents and timestamps</strong> &mdash; needed to generate a
relevant reply and to keep conversation context.</li>
<li><strong>Business configuration</strong> supplied by the business owner
(business name, catalog, FAQs).</li>
</ul>

<h2>How we use it</h2>
<ul>
<li>To generate AI replies to incoming WhatsApp messages.</li>
<li>To keep short-term conversation history so follow-up messages make sense.</li>
<li>To operate and debug the demo (e.g. error logs).</li>
</ul>

<h2>Sharing</h2>
<p>Messages are processed by <strong>Meta's WhatsApp Cloud API</strong> (message
delivery) and <strong>Groq</strong> (AI reply generation). We do not sell,
rent, or share personal data with advertisers or data brokers.</p>

<h2>Retention and deletion</h2>
<p>Conversation history is kept only as long as needed for the demo to function.
You can request deletion of your messages at any time via the contact below,
and we will remove them from our database.</p>

<h2>Children</h2>
<p>This demo is not directed at children under 13, and we do not knowingly
collect their data.</p>

<h2>Contact</h2>
<p>For privacy questions or deletion requests:
<a href="mailto:temp2saubhagya@gmail.com">temp2saubhagya@gmail.com</a></p>

<footer>Multi-Tenant WhatsApp Agent &mdash; demo project.</footer>
</body></html>
"""

TERMS_HTML = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Terms of Service &mdash; Multi-Tenant WhatsApp Agent</title>
<style>{_PAGE_STYLE}</style></head>
<body>
<h1>Terms of Service</h1>
<p class="updated">Last updated: October 1, 2026</p>
<p><strong>Multi-Tenant WhatsApp Agent</strong> is a personal demo/portfolio
project. By messaging a connected number or using the dashboard, you agree to
these terms.</p>

<h2>The service</h2>
<p>The demo provides AI-generated replies to WhatsApp messages on behalf of a
business. Replies are generated by a language model and may occasionally be
inaccurate &mdash; do not rely on them for medical, legal, financial, or other
high-stakes decisions.</p>

<h2>Acceptable use</h2>
<ul>
<li>Do not use the demo for spam, harassment, fraud, or anything unlawful.</li>
<li>Do not attempt to disrupt, scrape, or reverse-engineer the service.</li>
</ul>

<h2>Availability</h2>
<p>This is a demo running on free-tier infrastructure. It is provided
&ldquo;as is&rdquo;, without warranties of any kind, and may be unavailable at
times.</p>

<h2>Changes</h2>
<p>We may update these terms as the demo evolves; continued use means you accept
the current version.</p>

<h2>Contact</h2>
<p><a href="mailto:temp2saubhagya@gmail.com">temp2saubhagya@gmail.com</a></p>

<footer>Multi-Tenant WhatsApp Agent &mdash; demo project.</footer>
</body></html>
"""


@router.get("/privacy", response_class=HTMLResponse)
async def privacy_policy():
    return PRIVACY_HTML


@router.get("/terms", response_class=HTMLResponse)
async def terms_of_service():
    return TERMS_HTML
