import base64
import logging
from datetime import datetime
from uuid import uuid4

from google import genai
from google.genai import types

from app.agent.state import AgentState
from app.agent.tools import TOOLS
from app.config import settings
from app.db.mongodb import get_db
from app.rag.chroma_client import search_knowledge_base
from app.whatsapp import client as wa

logger = logging.getLogger(__name__)

_gemini_client = genai.Client(api_key=settings.gemini_api_key)
GEMINI_MODEL = settings.gemini_model

# Optional Groq fallback client (used only if Gemini fails / rate-limits)
_groq_client = None
if settings.groq_api_key:
    try:
        from groq import Groq
        _groq_client = Groq(api_key=settings.groq_api_key)
    except Exception as e:
        logger.warning(f"Groq fallback unavailable: {e}")


def _groq_text_fallback(system_prompt: str, state: AgentState) -> str | None:
    """Plain-text reply via Groq when Gemini is unavailable. No tool calling."""
    if not _groq_client:
        return None
    try:
        msgs = [{"role": "system", "content": system_prompt}]
        for m in (state.get("chat_history") or [])[:-1]:
            role = "user" if m["direction"] == "INBOUND" else "assistant"
            if m.get("text_content"):
                msgs.append({"role": role, "content": m["text_content"]})
        msgs.append({"role": "user", "content": state["inbound_text"]})

        resp = _groq_client.chat.completions.create(
            model=settings.groq_model,
            messages=msgs,
            temperature=0.5,
            max_tokens=400,
        )
        logger.info("[FALLBACK] reply generated by Groq")
        return resp.choices[0].message.content
    except Exception as e:
        logger.error(f"Groq fallback failed: {e}")
        return None

# Convert our tool defs to Gemini types.Tool format
_gemini_tools = [
    types.Tool(function_declarations=[
        types.FunctionDeclaration(
            name=t["name"],
            description=t["description"],
            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    k: types.Schema(type=types.Type.STRING, description=v.get("description", ""))
                    for k, v in t["parameters"]["properties"].items()
                },
                required=t["parameters"].get("required", []),
            ),
        )
        for t in TOOLS
    ])
]


# ---------------------------------------------------------------------------
# Node 1: Acknowledge
# ---------------------------------------------------------------------------

async def acknowledge_node(state: AgentState) -> AgentState:
    """
    Fires read receipt + typing indicator immediately.
    Saves inbound message to MongoDB.
    """
    phone_id = state["tenant_config"]["whatsapp_phone_number_id"] if state.get("tenant_config") else settings.meta_phone_number_id

    try:
        await wa.send_read_receipt(phone_id, state["whatsapp_message_id"])
    except Exception as e:
        logger.warning(f"Read receipt failed: {e}")

    try:
        await wa.send_typing_indicator(phone_id, state["whatsapp_message_id"])
    except Exception as e:
        logger.warning(f"Typing indicator failed: {e}")

    db = get_db()

    # Save inbound message
    await db.message_audit_log.insert_one({
        "message_id": str(uuid4()),
        "whatsapp_message_id": state["whatsapp_message_id"],
        "session_id": state["session_id"],
        "tenant_id": state["tenant_id"],
        "direction": "INBOUND",
        "sender": state["customer_phone"],
        "text_content": state["inbound_text"],
        "media_url": None,
        "media_type": state.get("inbound_media_type"),
        "agent_state": "TYPING",
        "is_read": True,
        "timestamp": datetime.utcnow(),
    })

    # Update session status
    await db.chat_sessions.update_one(
        {"session_id": state["session_id"]},
        {"$set": {"status": "AGENT_RESPONDING", "last_message_at": datetime.utcnow()}},
    )

    state["session_status"] = "AGENT_RESPONDING"
    return state


# ---------------------------------------------------------------------------
# Node 2: Context Retriever
# ---------------------------------------------------------------------------

async def context_retriever_node(state: AgentState) -> AgentState:
    """
    Fetches tenant config, last 5 messages, RAG chunks.
    Bonus B2: if user sent image, analyses with Gemini Vision.
    """
    db = get_db()

    # Tenant config
    tenant = await db.tenants.find_one({"tenant_id": state["tenant_id"]})
    if not tenant:
        state["error"] = f"Tenant {state['tenant_id']} not found"
        return state
    state["tenant_config"] = tenant

    # Last 5 messages (oldest first)
    msgs = await db.message_audit_log.find(
        {"session_id": state["session_id"]}
    ).sort("timestamp", -1).limit(5).to_list(5)
    state["chat_history"] = list(reversed(msgs))

    # RAG
    state["rag_chunks"] = search_knowledge_base(
        query=state["inbound_text"],
        tenant_id=state["tenant_id"],
    )

    # --- Visible flow logging ---
    logger.info(f"[INBOUND] ({tenant['name']}) customer said: {state['inbound_text']!r}")
    logger.info(f"[MONGODB] loaded {len(state['chat_history'])} prior messages from history")
    if state["rag_chunks"]:
        logger.info(f"[RAG/Chroma] found {len(state['rag_chunks'])} relevant knowledge chunks:")
        for i, c in enumerate(state["rag_chunks"], 1):
            logger.info(f"    [{i}] {c[:110]}...")
    else:
        logger.info("[RAG/Chroma] no relevant knowledge found -> LLM answers from system prompt only")

    # Bonus B2: Analyse inbound image with Gemini Vision
    if state.get("inbound_media_id"):
        try:
            media_url = await wa.get_media_url(state["inbound_media_id"])
            img_bytes = await wa.download_media(media_url)

            vision_resp = _gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=[
                    types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg"),
                    types.Part.from_text(text=(
                        "Describe this image concisely for a customer service agent. "
                        "Focus on: what product or item is shown, its appearance, condition, "
                        "color, style, and any details relevant to helping the customer."
                    )),
                ],
            )
            state["inbound_image_description"] = vision_resp.text
        except Exception as e:
            logger.warning(f"Gemini Vision failed: {e}")

    return state


# ---------------------------------------------------------------------------
# Node 3: LLM Reasoning
# ---------------------------------------------------------------------------

def _build_system_prompt(tenant: dict, rag_chunks: list) -> str:
    prompt = tenant["system_prompt"]

    # Tell the LLM EXACTLY what media files exist so it never promises
    # or re-sends something it doesn't have.
    media_lib = tenant.get("media_library", {})
    if media_lib:
        # Deduplicate by URL (e.g. 'catalog' and 'brochure' may share one file)
        seen_urls = {}
        for keyword, url in media_lib.items():
            seen_urls.setdefault(url, []).append(keyword)
        prompt += "\n\n--- MEDIA YOU CAN SEND (via get_media tool) ---\n"
        for url, keywords in seen_urls.items():
            kind = "PDF document" if url.lower().endswith(".pdf") else "image"
            prompt += f"- {kind}: ask with keyword '{keywords[0]}'\n"
        prompt += (
            "This is the COMPLETE list of files you have. You have exactly ONE file per item above.\n"
            "If a customer asks for 'more' images or something not in this list, do NOT re-send the same "
            "file. Instead, honestly say that's the piece you have on hand and offer the full *catalog* "
            "to see the complete range. Only call get_media when the customer actually wants to receive a file.\n"
            "--- END MEDIA LIST ---\n"
        )

    if rag_chunks:
        prompt += "\n\n--- RELEVANT KNOWLEDGE BASE ---\n"
        for i, chunk in enumerate(rag_chunks, 1):
            prompt += f"\n[{i}] {chunk}\n"
        prompt += "\n--- END KNOWLEDGE BASE ---\n"
        prompt += (
            "\nBase your answer on the knowledge base above. "
            "Do not fabricate prices, specs, or policies not mentioned."
        )
    return prompt


async def llm_reasoning_node(state: AgentState) -> AgentState:
    """
    Calls Gemini 2.5 Flash with tool calling.
    Handles get_media, search_knowledge, escalate_to_human tools.
    """
    if state.get("error"):
        state["llm_reply"] = "Sorry, I'm having technical difficulties. Please try again shortly."
        return state

    tenant = state["tenant_config"]
    system_prompt = _build_system_prompt(tenant, state.get("rag_chunks") or [])

    # Build conversation history for Gemini new SDK
    contents = []
    for msg in (state.get("chat_history") or [])[:-1]:
        role = "user" if msg["direction"] == "INBOUND" else "model"
        text = msg.get("text_content", "")
        if text:
            contents.append(types.Content(role=role, parts=[types.Part.from_text(text=text)]))

    # Current user message
    user_text = state["inbound_text"]
    if state.get("inbound_image_description"):
        user_text = (
            f"[Customer sent an image: {state['inbound_image_description']}]\n"
            f"{user_text}"
        )
    contents.append(types.Content(role="user", parts=[types.Part.from_text(text=user_text)]))

    try:
        response = _gemini_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                tools=_gemini_tools,
                temperature=0.4,
                automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
            ),
        )
    except Exception as e:
        logger.error(f"Gemini call failed: {e} -> trying Groq fallback")
        # Fallback: Groq for a plain-text reply (no media tools) so the bot stays alive
        fallback = _groq_text_fallback(system_prompt, state)
        state["llm_reply"] = fallback or "I'm experiencing a brief outage. Please try again in a moment."
        state["media_to_send"] = None
        state["media_type"] = None
        state["media_filename"] = None
        return state

    # Process response parts
    final_reply = None
    media_url = None
    media_type = None
    media_filename = None
    function_response_parts = []  # for the 2nd call (natural caption)

    candidate_parts = response.candidates[0].content.parts
    for part in candidate_parts:
        if part.function_call:
            fn = part.function_call
            fn_args = dict(fn.args) if fn.args else {}

            if fn.name == "get_media":
                keyword = fn_args.get("keyword", "").lower()
                logger.info(f"[LLM DECISION] called tool get_media(keyword={keyword!r}) -> looking up MongoDB media_library")
                media_lib = tenant.get("media_library", {})
                matched_key = None
                for key, url in media_lib.items():
                    if keyword in key.lower() or key.lower() in keyword:
                        media_url = url
                        matched_key = key
                        if url.lower().endswith(".pdf"):
                            media_type = "DOCUMENT"
                            media_filename = f"{key.title().replace(' ', '_')}.pdf"
                        else:
                            media_type = "IMAGE"
                        logger.info(f"[MEDIA LIBRARY] matched {key!r} -> {media_type}: {url}")
                        break
                # get_media outcome is deterministic — write a contextual caption locally.
                # This deliberately AVOIDS a 2nd Gemini call (saves the free-tier budget).
                if matched_key:
                    pretty = matched_key.title()
                    if media_type == "DOCUMENT":
                        final_reply = f"Here's our *{pretty}* 📄 — take a look and tell me what catches your eye!"
                    else:
                        final_reply = f"Here's the *{pretty}* 😊 Let me know if you'd like to see more."
                else:
                    final_reply = (
                        "That's the piece I have on hand right now. "
                        "Would you like me to send our full *catalog* to see the complete range?"
                    )

            elif fn.name == "search_knowledge":
                extra_query = fn_args.get("query", "")
                extra = search_knowledge_base(extra_query, state["tenant_id"])
                existing = state.get("rag_chunks") or []
                state["rag_chunks"] = existing + [c for c in extra if c not in existing]
                function_response_parts.append(
                    types.Part.from_function_response(
                        name="search_knowledge",
                        response={"results": extra[:3] if extra else "no additional info found"},
                    )
                )

            elif fn.name == "escalate_to_human":
                state["session_status"] = "NEEDS_HUMAN"
                final_reply = (
                    "I completely understand, and I'm so sorry for the frustration. "
                    "I'm bringing in one of our human specialists right now to personally take care of "
                    "this for you. They'll reach out very shortly. 🙏"
                )

        elif part.text:
            final_reply = part.text

    # Two-step function calling: if a tool ran, ask Gemini to write a natural reply
    if function_response_parts and not final_reply:
        try:
            contents.append(response.candidates[0].content)            # model's tool-call turn
            contents.append(types.Content(role="user", parts=function_response_parts))  # tool results
            followup = _gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=contents,
                config=types.GenerateContentConfig(
                    system_instruction=system_prompt,
                    temperature=0.5,
                ),
            )
            final_reply = followup.text
        except Exception as e:
            logger.warning(f"Caption follow-up failed: {e}")

    # Last-resort fallback (only if everything above produced nothing)
    if not final_reply:
        if media_type == "DOCUMENT":
            final_reply = "Here you go! 📄 Let me know if anything catches your eye."
        elif media_type == "IMAGE":
            final_reply = "Here it is! 😊 Want to see more pieces? I can share our full catalog."
        else:
            final_reply = "I'm here to help! Could you tell me a bit more about what you're looking for?"

    state["llm_reply"] = final_reply
    state["media_to_send"] = media_url
    state["media_type"] = media_type
    state["media_filename"] = media_filename

    logger.info(f"[REPLY] {state['llm_reply'][:150]!r}")
    if media_url:
        logger.info(f"[REPLY] + attaching {media_type}: {media_filename or media_url}")
    logger.info(f"[STATUS] session -> {state['session_status']}")

    return state


# ---------------------------------------------------------------------------
# Node 4: Dispatcher
# ---------------------------------------------------------------------------

async def dispatcher_node(state: AgentState) -> AgentState:
    """
    Sends WhatsApp reply (text + optional media).
    Saves outbound message to MongoDB.
    Updates session status.
    Typing indicator auto-stops when a message is sent.
    """
    phone_id = state["tenant_config"]["whatsapp_phone_number_id"]
    to = state["customer_phone"]
    db = get_db()

    try:
        await wa.send_text_message(phone_id, to, state["llm_reply"])
    except Exception as e:
        logger.error(f"Failed to send text message: {e}")

    if state.get("media_to_send"):
        try:
            if state["media_type"] == "IMAGE":
                await wa.send_image_message(phone_id, to, state["media_to_send"])
            elif state["media_type"] == "DOCUMENT":
                await wa.send_document_message(
                    phone_id, to, state["media_to_send"], state["media_filename"]
                )
        except Exception as e:
            logger.error(f"Failed to send media: {e}")

    # Determine final status
    new_status = state["session_status"] if state["session_status"] == "NEEDS_HUMAN" else "RESOLVED"

    # Save outbound message
    await db.message_audit_log.insert_one({
        "message_id": str(uuid4()),
        "session_id": state["session_id"],
        "tenant_id": state["tenant_id"],
        "direction": "OUTBOUND",
        "sender": "BOT",
        "text_content": state["llm_reply"],
        "media_url": state.get("media_to_send"),
        "media_type": state.get("media_type"),
        "media_filename": state.get("media_filename"),
        "agent_state": "SENT",
        "timestamp": datetime.utcnow(),
    })

    # Update session
    await db.chat_sessions.update_one(
        {"session_id": state["session_id"]},
        {
            "$set": {"status": new_status, "last_message_at": datetime.utcnow()},
            "$inc": {"message_count": 2},
        },
    )

    state["session_status"] = new_status
    return state
